spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
          - name: AB_JOLOKIA_OFF
            value: 'true'
